CREATE ROLE ap_admin;
CREATE ROLE manager;
CREATE ROLE seller;
CREATE ROLE provider;

CREATE USER username IDENTIFIED BY passwords DEFAULT TABLESPACE_USERS TEMPORARY TABLESPACE_TEMP;
GRANT CONNECT TO username;

GRANT ap_admin TO username;

GRANT ALL PRIVILEGES TO ap_admin;
GRANT INSERT, UPDATE, DELETE ON ACCOUNTING TO manager;
GRANT INSERT, UPDATE, DELETE ON CUSTOMERS TO manager;
GRANT INSERT, UPDATE, DELETE ON DELIVERIES_GOODS TO manager;
GRANT INSERT, UPDATE, DELETE ON DELIVERIES TO manager;
GRANT INSERT, UPDATE, DELETE ON PROVIDER TO manager;
GRANT INSERT, UPDATE, DELETE ON GOODS TO manager;
GRANT INSERT, UPDATE, DELETE ON PURCHASE_COMPOSITIONS TO manager;
GRANT INSERT, UPDATE, DELETE ON SALES TO manager;
GRANT INSERT, UPDATE, DELETE ON SELLER TO manager;
GRANT INSERT, UPDATE, DELETE ON TRADE_POINTS TO manager;
GRANT INSERT, UPDATE, DELETE ON TRADE_ROOM TO manager;
GRANT INSERT, UPDATE, DELETE ON TRADE_SECTION_POINT TO manager;
GRANT INSERT, UPDATE, DELETE ON TRADE_TYPES TO manager;

GRANT INSERT, UPDATE, DELETE ON SALES TO seller;
GRANT INSERT, UPDATE, DELETE ON PURCHASE_COMPOSITIONS TO seller;
GRANT INSERT, UPDATE, DELETE ON CUSTOMERS TO seller;
GRANT INSERT, UPDATE, DELETE ON ACCOUNTING TO seller;

GRANT INSERT, UPDATE, DELETE ON DELIVERIES TO provider;
GRANT INSERT, UPDATE, DELETE ON DELIVERIES_GOODS TO provider;
GRANT INSERT, UPDATE, DELETE ON GOODS TO provider;